### ISSUE TITLE
Should MIME types be per connection, or per request?

### ISSUE THREAD

**Issue by vjn** [rsocket/rsocket#117]
Currently, MIME types for the metadata and data frames are specified in the SETUP frame, so once per connection. However, given that like in HTTP (/2), a client and a server will only have a single connection, and different requests have different purposes, isn't it better to have the data MIME type at the request level, just like in HTTP?

Optionally, if no middleware/brokers are expected that will look into request/response frames based on MIME type, perhaps the MIME type is unnecessary?

**Comment by vjn** [comment]
Discussed with @benjchristensen and Ondrej:

- application/x-binary as a default, if nothing is specified.
- in the SETUP frame, make the MIME types optional (flag to say whether MIME is specified).
- in the REQUEST* frames, also, under flag control, optionally include MIME types.

**Comment by tmontgomery** [comment]
As long as the MIME type can be specified as a constant for a connection so that applications are NOT required to specify it with reach frame, then this should be fine.

**Comment by yschimke** [comment]
n.b. lesson from HTTP, sometimes this is a negotiation or the client can't know before making the request what the response mime type will be.  So making it optionally part of RESPONSE also would be useful.

**Comment by NiteshKant** [comment]
My thoughts on mime-types for reactive-socket:

#### Homogeneous mime-types

I believe for internal service to service communication, it would always be one homogeneous mime-type for the connection. This is what we have as part of setup.

#### Heterogeneous mime-types

This would be the case for browser-based traffic or the traffic on the edge (internet). There are two options here:

- We already have [default metadata format](https://github.com/ReactiveSocket/reactivesocket/blob/master/MimeTypes.md) which provides a name-value pair semantics to provide any metadata. This can be utilized to pass around per request mime-type. We can specify standard metadata key for mime-type if required.
- Most likely reactive-socket would be running over HTTP/2 for browser traffic. Since, HTTP/2 already have content-type header, can we utilize that to provide mime-type per requests?

I would like to limit complexity on the protocol layer and providing a flag per request for mime-type looks like a complexity that can be avoided based on my understanding as described above.

**Comment by vjn** [comment]
Given that the setup frame also can have metadata, for consistency, would it be better to do the same for the _default_ MIME types for the connection as for the optional per-request metadata?

Echoing what @yschimke said, I think that its logical to expect different requests (that is, to different resources, based on the data) to return possibly different MIME type-encoded data. In that case, following HTTP, perhaps the requester would also need to be able to specify a chosen format/sets of formats?

**Comment by NiteshKant** [comment]
@vjn my argument here is that different encoding are relevant primarily for browser traffic or the traffic from the internet where disparate applications will use the same underlying `ReactiveSocket` connection. For this case, most likely `ReactiveSocket` would be running on top of HTTP/2, which already provides mime-type(content-type, accept-encoding, etc.) headers. So, IMO, if we do support heterogeneous mime-types, we would be re-inventing what HTTP/2 already does and does it well. So, is there a strong reason to do that?

**Comment by vjn** [comment]
@NiteshKant, lets consider the two cases. If we're running on top of HTTP/2, since that supports MIME types, we don't have to have it at all. If we're not running on top of such a protocol, then we can: support 0, 1 or many MIME types: after all, we have metadata push, and per-request metadata as choices. Seems like we picked 1, wondering whether that is a general-enough choice.

**Comment by benjchristensen** [comment]
I suggest this does not need to be decided upon for v1.0. 

With the current protocol, a particular use can always use the per-stream metadata to do this if it needs to. And we can evolve the protocol later with supported versioning if it becomes strongly needed. 

At this time it is primarily an idea and in my opinion not important enough to do prior to v1.0.

**Comment by vjn** [comment]
Agree that this is not important for 1.0.

**Comment by yschimke** [comment]
@vjn @benjchristensen I'm going to go out on a limb and say we are happy with this for 1.0, and if we want this later we should reopen this ticket.

**Comment by viniciusccarvalho** [comment]
Hi there, I'd welcome a per-stream metadata, given that one service could expose heterogenous types depending on the invocation. For most exchange modes this makes total sense, as there's only a single request from the client. 

On the channel mode however it looks a bit of overkill having the mime type sent on every Payload after the first one, it feels like there's a missing step on that mode where after a successful connection client and server could exchange a session for the stream that is suppose to be exchange between them.

**Comment by yschimke** [comment]
Metadata is optional on those payload messages, so you can use metadata for the initiating request, and even the first response, then drop after that.
