### ISSUE TITLE
Server honors leases setup

### ISSUE THREAD

**Issue by NiteshKant** [rsocket/rsocket#145]
Carrying over the discussion from [here](https://github.com/ReactiveSocket/reactivesocket-java/pull/216#discussion_r94628236)

Setup frame allows for a client to suggest whether it will honor leases from the server or not. However, there is no way for the server to suggest whether it will honor leases from the client or not. 

Is this an oversight or intentional? If an oversight, should we fix it?

**Comment by benjchristensen** [comment]
Does it make sense to use leasing in a 1:1 relationship, such as exists for calls from the server to the client? The only benefit I see is making a request fail before going over the network. Which is potentially a good benefit if it is all configured well. But that's not generally what we've added leasing for, which is choosing which of many servers to send a request/response to in a stateless server-to-server environment with pools of connections.

**Comment by tmontgomery** [comment]
I believe the original idea was to make it symmetric. In that if LEASE was set, then both ends did it. One could set the lease quite high, though.

**Comment by benjchristensen** [comment]
If it is to be symmetric then, sounds like it should be clarified?

**Comment by NiteshKant** [comment]
I agree that it is simpler and better to make it symmetric (if client honors leases, server must do so too) and yes we need to clarify. I will send a PR as the first pass and we can discuss the language.

**Comment by benjchristensen** [comment]
Thanks, I'll watch for the PR.

**Comment by benjchristensen** [comment]
Anything on this that you want to get in soon?

**Comment by fiorix** [comment]
My understanding from the protocol spec is that if clients set the L flag in the setup then it expects the server to give it a lease. The client giving a lease to the server seemed optional (seq 1 of the [Sequences with Lease](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#sequences-with-lease) section).

In order for the server to make requests it must wait for the client to give it a lease, which is not necessarily the same.

This also raises another question to me: are leases only to drive the pace of requests, but not responses? If the point of having leases is to somehow pace clients in terms of server and network usage, it would not guarantee that responses can't cause HOL problems. Thus, in case responses must abide to leases, a client must always provide a lease to the server in order for the server to respond.

Does this make sense or am I missing something?

**Comment by yschimke** [comment]
The protocol here looks pretty clear, that both sides should issue leases and without it the server can't submit requests back to the client.

reopen if I misunderstand
