### ISSUE TITLE
TLS application-layer protocol negotiation (ALPN) identifier for rsocket

### ISSUE THREAD

**Issue by fiorix** [rsocket/rsocket#181]
We should probably define the string to identify ReactiveSockets over TLS+ALPN in the protocol specification. This would allow us to serve ReactiveSockets alongside other protocols in the same port over TLS.

For reference, the HTTP/2 section on this topic: https://tools.ietf.org/html/rfc7540#section-3.1

**Comment by fiorix** [comment]
When ReactiveSockets are transported over HTTP/2 (or WebSockets over HTTP/1), we should also define the expected Content-Type header for requests and responses, e.g. `application/rsocket` or something along those lines. gRPC uses `application/grpc` for this.

This would also allow us to serve ReactiveSockets alongside other HTTP/2 traffic in the same port.

**Comment by yschimke** [comment]
n.b. I'm not sure what ReactiveSocket over HTTP/2 *is* is actually written down yet.  Is it TCP encoding over a single HTTP/2 stream, or is it ReactiveSocket frames as an extension of HTTP/2.  see https://github.com/ReactiveSocket/reactivesocket/issues/84

**Comment by tmontgomery** [comment]
Yes, this should be addressed. But I don't think it needs to be for 1.0.

**Comment by fiorix** [comment]
Can't we commit to a few identifiers before 1.0?

I'd like propose these:

* "rs" for the ALPN identifier, the two-octet sequence: 0x72, 0x73
* HTTP Content-Type header: "application/rsocket"

Unlike gRPC (see the [wire](http://www.grpc.io/docs/guides/wire.html) format) we don't need to pass the serialisation format in the Content-Type because that info is carried over by SETUP frames.

**Comment by benjchristensen** [comment]
> This would also allow us to serve ReactiveSockets alongside other HTTP/2 traffic in the same port.

We are already doing this today, but yes, would be good to standardize the identifiers. 

> identifiers

- "rs" for the ALPN identifier, the two-octet sequence: 0x72, 0x73
- HTTP Content-Type header: "application/rsocket"

I'm happy with those. Does anything need to be done formally for either of those?

**Comment by benjchristensen** [comment]
@tmontgomery Is there anything regarding this to be done such that we don't have issues post v1.0?

**Comment by tmontgomery** [comment]
It would be good to grab the ALPN and HTTP Content-Type values. (I have no strong feelings, so @fiorix proposal seems good).

**Comment by tmontgomery** [comment]
IANA is probably the controlling agency for the ALPN and maybe the HTTP Content-Type (HTTP is sometimes under W3C instead... IIRC).

**Comment by tmontgomery** [comment]
No. Looks like IANA does media types as well.

**Comment by fiorix** [comment]
For ref.

ALPN: http://www.iana.org/assignments/tls-extensiontype-values/tls-extensiontype-values.xhtml#alpn-protocol-ids

Content-type: http://www.iana.org/assignments/media-types/media-types.xhtml

**Comment by benjchristensen** [comment]
So, what action do we need to take for this?

**Comment by tmontgomery** [comment]
I think it can be looked at 2 ways.

1. We grab the ALPN and Content-type because they are used or will shortly be used, or
2. We wait until the ALPN and Content-type are needed and grab them then.

If use of these is imminent, then definitely grab them. If not imminent, but we think it will be needed anyway, grab them. If neither, we can hold off.

**Comment by lexs** [comment]
Did we ever grab these? We've started using "rs" internally as the ALPN type.

**Comment by yschimke** [comment]
The websocket upgrade over HTTP/2 spec is very generic and would work well for HTTP/2 support here.

https://datatracker.ietf.org/doc/draft-ietf-httpbis-h2-websockets/?include_text=1

In which case we should also register an upgrade token

https://www.iana.org/assignments/http-upgrade-tokens/http-upgrade-tokens.xhtml
