### ISSUE TITLE
Checksumming

### ISSUE THREAD

**Issue by benjchristensen** [rsocket/rsocket#208]
Question brought up about whether this protocol should do checksums.

Supporting evidence of "bad things happening":

- https://fb.facebook.com/notes/ramkumar-natarajan/bitflips-in-event-configuration/10157088119540006
- https://criticalindirection.com/2016/02/22/tcp-checksum-the-fault-in-the-stars/

The concern expressed is that a bit flips and the protocol ends up in a "zombie" state where a stream dangles or other non-deterministic behavior occurs.

**Comment by benjchristensen** [comment]
I can't imagine choosing the computational and data costs of checksumming every frame, and just accepting the risk of a bit flip happening and possibly causing odd behavior, such as a hung stream. 

But should the protocol allow something different? Or should the answer be left to the transport layer, which was my initial response as to what is responsible for this (https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#transport-protocol).

**Comment by tmontgomery** [comment]
It's a question of probability and consequence. So, a risk assessment.

There is a timeout implied in the protocol. So, any corruption (to the rsocket header) that causes a misstep should cause a timeout. If the implementation has sufficient validation, that is. However, corruption of payload may will result in application corruption.

By and large, data payloads (metadata or data) have a higher probability of corruption than headers/footers.

So, a possible solution is a checksum as part of the metadata. Would be better if metadata could follow data, though.

Checksums can be quite performant when done correctly.

Remember that simply reflecting the same checksum from the transport/network layer provides no more protection unless it is done differently. Different checksums are better than reusing the same one.

**Comment by tmontgomery** [comment]
Honestly, this is a framing issue and is probably best handled by the framing. i.e. just like framing is left to the transport, so to should the presence/absence of a checksum field for any checksum.

**Comment by nickgg** [comment]
My original question was actually aimed at the behavior of ignoring bad frames rather than checksumming. It's very low % but if say the stream id for a new REQUEST_CHANNEL gets corrupted and beats the TCP CRC check - in the leaseless scenario the requestor will start streaming packets which are silently ignored and the application on either side can't tell there's a problem.

It's (extremely) unlikely to occur, but if it does I can't see it as being anything other than a bug in the protocol. This is different from other protocols, I think, because the failure is silent and hidden from the user.

**Comment by wenbozhu** [comment]
Optional checksum on user-provided messages (data and metadata) needs be the responsibility of the RS protocol, IMO. Then applications above RS (which could be a dbms) won't have to checksum.

**Comment by tmontgomery** [comment]
@nickgg I think some of the handling within an implementation could be more stringent. i.e. if a server sees a request with a stream id that indicates a gap, it could error out the connection. Some of this is captured in the spec. Some not.

But, the handling of checksum failure in a reliable transport is often overlooked. What happens, for example, in RS if a frame fails to checksum? Dropping some frames can cause corruption (like dropping a single PAYLOAD out of stream). Or should a single checksum failure error the connection?

@wenbozhu I have argued it both ways in the past. In general, I do prefer checksumming of payload to be optional when possible. The best place to do it depends on the use case. That is why for example, in Aeron, we placed a reserved value field in the header to be filled by the application on send. This is used for checksumming by some users. It is easy to layer this functionally quite nicely.

**Comment by nickgg** [comment]
I'm not sure what you mean by a gap in the stream ids? The spec does not specify an ordering of stream ids.

I think its a reasonable call to push the problem of checksumming up to the user, but that's not possible for control packets such as SETUP and REQUEST_X.

**Comment by tmontgomery** [comment]
@nickgg the spec implies an ordering by referencing HTTP/2. But doesn't explicitly enforce it. The only part called out is the even/odd part. However, by referencing HTTP/2, it is bringing in some semantics in an implied manner.

It depends on what is meant by "user" honestly. The use of a specific transport is a user choice. Nothing is forbidden from using a transport that has a checksum or does something equivalent (such as an HMAC). The transport section is not meant to be exhaustive and if it was, RS would be in real trouble because it could not be future compatible.

Given the choice of transport and given that framing is broken out, I don't see why including checksum in the protocol is necessary. It feels like over specification to me.

**Comment by benjchristensen** [comment]
Is there anything right now that MUST be figured out before we call the spec v1.0? Or can this easily be added in future versions if we end up determining it is important?

I'd rather not rush a design on something like this, and it seems to me we could easily add it later in a v1.x by having new optional fields on frames.

**Comment by tmontgomery** [comment]
Nothing comes to mind for me. And as I have stated, I think checksumming can be done in the transport framing or at the application level.

**Comment by nickgg** [comment]
Sure, sounds fine.

I do think that if you intended to imply a sequential ordering to stream ids that should be explicit in the spec, to avoid interop gotchas.

**Comment by stevegury** [comment]
I agree with @tmontgomery here.
Let's keep this protocol simple and leave the checksum out of the picture, it can be added at different level if necessary.

**Comment by benjchristensen** [comment]
> I do think that if you intended to imply a sequential ordering to stream ids that should be explicit in the spec, to avoid interop gotchas.

@tmontgomery Should wording on this be clarified? For example, should we require starting at 1/2 and incrementing sequentially by 2 (odd/even on each side)?

**Comment by tmontgomery** [comment]
@benjchristensen For clarity, we should, I believe. Also, it does add a means to help validate a stream id.

**Comment by benjchristensen** [comment]
Proposed change here: https://github.com/ReactiveSocket/reactivesocket/pull/220

**Comment by yschimke** [comment]
I think agreement here was only to merge the above PR, and leave everything else out of scope or specific to a particular transport impl.
