### ISSUE TITLE
Ignoring frames

### ISSUE THREAD

**Issue by yschimke** [rsocket/rsocket#230]
> Metadata Length MUST be less than or equal to the Frame Length minus the length of the Frame Header. If Metadata Length is greater than this value, the entire frame MUST be ignored.

How does ignoring the frame make sense if it is the middle frame of 3 fragmented payloads?  Should this mean error/cancel the stream?

**Comment by fiorix** [comment]
That's my understanding from another conversation with @tmontgomery and you're allowed to cancel streams either transmitting or receiving fragments.

**Comment by yschimke** [comment]
https://github.com/rsocket/rsocket/pull/232/files
