### ISSUE TITLE
Metadata length question

### ISSUE THREAD

**Issue by josephsavona** [rsocket/rsocket#231]
From https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#metadata-optional-header:

> Metadata Length MUST be less than or equal to the Frame Length minus the length of the Frame Header. If Metadata Length is greater than this value, the entire frame MUST be ignored.

The only reason it could be less than the mentioned quantity is if there is payload data. Should this instead be "Metadata Length MUST be **equal** to the frame length minus the sum of (the length of the frame header + length of the frame payload, if present)"?

**Comment by benjchristensen** [comment]
Read this a few times, and I think you're right that it could be made exact as you say. 

@tmontgomery What do you think of the wording change?

**Comment by tmontgomery** [comment]
Yes, wording change should be good.
