### ISSUE TITLE
question about openid connect support

### ISSUE THREAD

**Issue by pavsh** [rsocket/rsocket#243]
Hi,
does reactivesocket for web sockets support openId connect auth?
thanks.

**Comment by yschimke** [comment]
No, not currently and it hasn't come up before AFAIK.  

Assuming you mean this general flow https://github.com/martinpaljak/authenticated-websocket with text websocket messages exchanged before the normal application payloads are sent.

Here are the rsocket-java and rsocket-js connections, which would either have to be extended to support this handshake, or allow for extension.  Or alternatively you could customise these as examples and have your own DuplexConnection type.

https://github.com/rsocket/rsocket-java/blob/1.0.x/rsocket-transport-netty/src/main/java/io/rsocket/transport/netty/WebsocketDuplexConnection.java

https://github.com/rsocket/rsocket-js/blob/master/packages/rsocket-websocket-client/src/RSocketWebSocketClient.js
