### ISSUE TITLE
extra flag in setup frame

### ISSUE THREAD

**Issue by natronjb** [rsocket/rsocket#247]
I'm looking at putting together a minimal rsocket client in C so I've been digging through the protocol definition and looking at the debug output from the java/netty implementation and comparing things, trying to make sure I understand everything that's going on.  I've got a quick question about the setup frame.  I'm seeing a bit set in the flags field but I don't see a description of that flag in the protocol definition.

https://github.com/rsocket/rsocket/blob/master/Protocol.md#frame-setup

Here's what I see the client send to the server:

             +-------------------------------------------------+
             |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
    +--------+-------------------------------------------------+----------------+
    |00000000| 00 00 3b 00 00 00 00 05 20 00 01 00 00 00 00 13 |..;..... .......|
    |00000010| 88 00 00 27 10 12 61 70 70 6c 69 63 61 74 69 6f |...'..applicatio|
    |00000020| 6e 2f 62 69 6e 61 72 79 12 61 70 70 6c 69 63 61 |n/binary.applica|
    |00000030| 74 69 6f 6e 2f 62 69 6e 61 72 79 00 00 00       |tion/binary...  |
    +--------+-------------------------------------------------+————————+

The interesting part is the '05 20' in the middle of the top line.  I see that line start with 00 00 3b, which is the length of the frame, then 00 00 00 00 which is the stream id (... of 0.  So far so good).

But then the 05 20 is throwing me off.  The first 6 bits is the frame type, which is 1, which means this is a setup frame.  Bits 6 and 7 (the 7th and 8th bits) are the Ignore and Metadata bits.  Only the metadata bit is set.

(BTW, it took me a while to figure out that the trailing 00 00 00 at the end of the frame was the metadata length... I'm assuming that NOT setting the metadata flag in the setup frame is legal, so long as you don't have any metadata, right?  In which case, there'd be no trailing 00 00 00?  Or does the setup frame always need the metadata bit set?)

The next two bits are both 0 - these are the Resume Enable and Lease flags, neither of which are set.  But the 3rd bit in the 2nd byte is set (hence the 2 in 05 20).  But there's no description of what that flag is.  Is it just a bonus flag that means I'm awesome?  Or is there a deeper meaning?

**Comment by yschimke** [comment]
I think it's a legacy flag that we should remove, thanks for flagging (pun intended).

https://github.com/rsocket/rsocket/pull/233/files

n.b. the rsocket-cli can help with testing and examining payloads e.g.

```
$ rsocket-cli --setup "Hello" --debug tcp://localhost:9898
04:57:58.931	[id: 0xa2a36b85, L:/127.0.0.1:61289 - R:localhost/127.0.0.1:9898] WRITE: 65B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 3e 00 00 00 00 05 20 00 01 00 00 00 00 75 |..>..... ......u|
|00000010| 30 00 01 5f 90 10 61 70 70 6c 69 63 61 74 69 6f |0.._..applicatio|
|00000020| 6e 2f 6a 73 6f 6e 12 61 70 70 6c 69 63 61 74 69 |n/json.applicati|
|00000030| 6f 6e 2f 62 69 6e 61 72 79 00 00 00 48 65 6c 6c |on/binary...Hell|
|00000040| 6f                                              |o               |
+--------+-------------------------------------------------+----------------+
```

**Comment by natronjb** [comment]
Awesome.  Thanks so much.
