### ISSUE TITLE
Can demand be unbounded?

### ISSUE THREAD

**Issue by nebhale** [rsocket/rsocket#251]
The spec is [quite explicit](https://github.com/rsocket/rsocket/blame/master/Protocol.md#L1201) that the Reactive Streams unbounded demand ([3.17](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.2/README.md#3-subscription-code)) isn't supported due to the different sizes of the available requests.  Is the RSocket maximum considered unbounded in it's stead or is there just no concept of a unbounded demand?

**Comment by yschimke** [comment]
No concept of unbounded, so assumes your app or the framework e.g. rsocket-android/rxjava or rsocket-java/reactor-core will keep topping up credits when you get through 2^31 - 1.

**Comment by nebhale** [comment]
Sounds good.  Can we add something to that effect in that paragraph?  Just to make it explicit?

**Comment by yschimke** [comment]
IMHO I don't think the spec should refer to specific implementations or libraries, and is clear to me as is.  Feel free to submit a PR with clarified wording.

**Comment by nebhale** [comment]
Will do, thanks.
