### ISSUE TITLE
New NIL Frame Type

### ISSUE THREAD

**Issue by linux-china** [rsocket/rsocket#277]
# Background
Now we want to adopt RSocket for NoSQL products, such as Cache, Redis and other NoSQL products. For these products,  there is a "Hit Rating" feature,  for example,  hit rating for cache iss almost from 50-100%, and it means lots of nil data response.   Nil has special meaning, and almost developers don't want to use Error or Payload as frame type,  and reasons as following:

*  Error type is not good for nil: it's not error, just no data there, and it's normal for these products.
*  Payload type: it's not good for statistics to use filter or interceptor,  and you need to touch the data and validate data empty or not. If no zero copy support, and performance problem.

# Solution
To introduce NIL frame type,  and make response frame types as following:

* Payload: good, the responder will give you data and optional metadata
* Nil:  no data, just return frame header 
* Error:  some error from responder

For Nil frame type, the responder just return following frame,  and the frame is fixed or static(stream id change) almost, and performance is good and no need to construct response payload at all.

```
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 06 00 00 00 01 28 40                      |.......(@       |
+--------+-------------------------------------------------+----------------+
```

the Nil is good both for request/response, request/stream. 

# Summary
Nil is normal for Cache, NoSQL products, and it's normal to query database.  Now RSocket does not have frame type extension, and some hard to extend this frame.  I think NIL should be included by default because it's very common.   I have no idea abut NIL or NULL because some Java developers are sensitive about NULL.

**Comment by yschimke** [comment]
I think this breaks the reactive stream spec, which specifies that a null payload to onNext must thow a NullPointerException https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.3/README.md#specification

> Calling onSubscribe, onNext, onError or onComplete MUST return normally except when any provided parameter is null in which case it MUST throw a java.lang.NullPointerException to the caller

It's already possible to encode a final payload frame on stream without data.  

> Just (C)omplete set meaning PAYLOAD contains no data and only signals stream completion. 

https://github.com/rsocket/rsocket/blob/master/Protocol.md#frame-payload

It is not possible to encode a frame without data that does not complete the stream. e.g. [A, NULL, C]

> A PAYLOAD MUST NOT have both (C)complete and (N)ext empty (false).

**Comment by linux-china** [comment]
>>> Just (C)omplete set meaning PAYLOAD contains no data and only signals stream completion.

How about this, just trigger Complete through RSocket.   Now we can return Mono.empty() or Flux.empty() for requester, could we make this case easy in RSocket?

**Comment by robertroeser** [comment]
If we're talking about rsocket-java than if you return a Mono.empty or Flux.empty it'll do that right now:
requestReply
https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/RSocketResponder.java#L423

requestStream / requestChannel
https://github.com/rsocket/rsocket-java/blob/develop/rsocket-core/src/main/java/io/rsocket/RSocketResponder.java#L466

**Comment by linux-china** [comment]
@robertroeser  right. Now I use this empty() for this case, but still Payload Frame Type,  but you know some legacy protocol and monitoring requirements.    Payload, NIL and Error are easy for developers to understand, just submit for later consideration.
