### ISSUE TITLE
Long usernames support for Simple Authentication Type

### ISSUE THREAD

**Issue by vdshb** [rsocket/rsocket#289]
Based on: https://github.com/rsocket/rsocket/blob/master/Extensions/Security/Simple.md

127 bytes for username in UTF-8 seems too strong limitation. UTF-8 char itself might consume 4 bytes, so in worst case scenario the limit is 31 characters. 4-byte chars should rarely be placed in username, but I don't think the protocol should put such short limitation anyway.

It's several strategies to improve this situation, but I think that as username-password authentication is pretty rare operation, so it worse to keep it simple and just increase **Username Length** field up to e.g. 16 bits. I believe 16383 chars are enough for any username situation.

**Comment by OlegDokuka** [comment]
I'm not sure I can speak on the security topic; however, there should 255 chars for a username (see #287).

Nevertheless, I would address this issue to @rwinch.

Regards,
Oleh

**Comment by vdshb** [comment]
Yes, thanks. +1 bit looks better, but it's still 255 bytes which are 63 **guaranteed chars** or 255 **optimistic chars** in UTF-8. I still think we should consider higher limits at early stage. 

+1 byte shouldn't get any performance issues (1-5% of average frame size), but it'll release application developers from such limitation. 31-63 change makes people with long email in Japanese locale be able to authenticate, but still prevent some rare cases, when some e.g. bots use long tokens as logins in some situations.
