### ISSUE TITLE
Cannot dispose server

### ISSUE THREAD

**Issue by sleoniy** [rsocket/rsocket#296]
React Netty recently updated its library so that calling dispose() terminates the server. When will a working dispose be available.

**Comment by linux-china** [comment]
any link?

**Comment by OlegDokuka** [comment]
@sleoniy This is not an appropriate channel to ask questions on rsocket-java issue. Please recreate at RSocket-Java

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
