### ISSUE TITLE
Jitter for KEEP ALIVE frames

### ISSUE THREAD

**Issue by SerCeMan** [rsocket/rsocket#307]
Hey, folks! 

## Motivation

In some situations, e.g. an unplanned interruption, a large number of clients might reconnect to the servers. In these cases, it's possible to observe that the client's keepalive frames are synchronised and behave like a wave after wave after wave as demonstrated on this graph:

_keepalive frame rate_
<img width="1400" alt="Screen Shot 2020-07-31 at 9 45 43 pm" src="https://user-images.githubusercontent.com/1780970/89032262-a3268100-d377-11ea-8d60-31c7cc1d2568.png">

While keep-alive frames are cheap to process, it feels like it would be great if we could avoid these synchronized on the protocol level by smoothing them out over time.   

## Desired solution

I believe introducing optional jitter of the keepalive frames could allow for smoothing the wave over time. However, at the moment, the spec requires fixed `Time Between KEEPALIVE Frames`, and it's not very clear whether the behaviour where clients add jitter to KA is allowed by the spec. It would be great if we could clarify this so that the rsocket libraries can incorporate jitter for KA frames.

**Comment by OlegDokuka** [comment]
Can every client generate a random keepalive within a specific range to avoid that? If so, it can be a workaround which should smooth such waves

**Comment by SerCeMan** [comment]
Ah, that's a really good idea, random intervals can help to achieve the same without adding any jitter at all, thanks!

**Comment by OlegDokuka** [comment]
Yup. I guess if we going to introduce jitter delay for keepalive as an extra configuration, it would lead the server to synchronize all the connections, which would be a drastic change to the existing implementations. Thus if a random interval will work smoothly, I would avoid this change.

Let me know if it worked for you

**Comment by OlegDokuka** [comment]
Hi @SerCeMan!

Any chance to prove the mentioned assumption?

Cheers,
Oleh

**Comment by OlegDokuka** [comment]
@SerCeMan closing this one. Feel free to reopen it if anything
